### PR TITLE
Bump to v0.2.0

### PR DESCRIPTION
**Pull request by mheon**
As the title says.

### CODE REVIEW

**Comment by mheon** [comment]
@Luap99 @baude @rhatdan PTAL

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
I still don't have push permissions to this repo so I can't push the tag.

**Comment by rhatdan** [comment]
@mheon @Luap99 I added both of you as admin of this repo.

**Pull request merged**
