### PR TITLE
Fix using the plugin without ports

### LINKED ISSUE #11413: Cannot create networks using docker-compose when using podman machine on macOS
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When creating networks via docker compose, functionality which worked via virtualbox no longer works with `podman machine`.

**Steps to reproduce the issue:**

1. Create a `docker-compose.yml`:

```
services:
  testservice:
    image: docker.io/alpine:latest
    volumes:
      - "testvol:/testvol"
    networks:
      - "testservice-net"

networks:
  testservice-net:

volumes:
  testvol:
```

2. Run `docker-compose up`

**Describe the results you received:**

```
Creating testnet_testservice_1 ... error

ERROR: for testnet_testservice_1  error preparing container 7f29fd8fa219a202ee08af5609f8cd9638d40f65cc0fdae3f9e25caa4f4c85f4 for attach: error configuring network namespace for container 7f29fd8fa219a202ee08af5609f8cd9638d40f65cc0fdae3f9e25caa4f4c85f4: error adding pod testnet_testservice_1_testnet_testservice_1 to CNI network "testnet_testservice-net": unexpected end of JSON input

ERROR: for testservice  error preparing container 7f29fd8fa219a202ee08af5609f8cd9638d40f65cc0fdae3f9e25caa4f4c85f4 for attach: error configuring network namespace for container 7f29fd8fa219a202ee08af5609f8cd9638d40f65cc0fdae3f9e25caa4f4c85f4: error adding pod testnet_testservice_1_testnet_testservice_1 to CNI network "testnet_testservice-net": unexpected end of JSON input
ERROR: Encountered errors while bringing up the project.
```

**Describe the results you expected:**

A working service with a network.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.17
Built:        Mon Aug 30 15:15:26 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.3.0
API Version:  3.3.0
Go Version:   go1.16.6
Built:        Fri Aug 20 15:36:14 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
Client:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.17
Built:        Mon Aug 30 15:15:26 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.3.0
API Version:  3.3.0
Go Version:   go1.16.6
Built:        Fri Aug 20 15:36:14 2021
OS/Arch:      linux/amd64
(base) ➜  testnet podman info --debug
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: localhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.12-200.fc34.x86_64
  linkmode: dynamic
  memFree: 593076224
  memTotal: 2061852672
  ociRuntime:
    name: crun
    package: crun-0.21-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.21
      commit: c4c3cdf2ce408ed44a9e027c618473e6485c635b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 37m 49.16s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 1
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 16
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.0
  Built: 1629488174
  BuiltTime: Fri Aug 20 19:36:14 2021
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.3.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Installed via homebrew
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Local MacBook Pro

### PR DESCRIPTION
**Pull request by Luap99**
When no ports are set we still have to return the CNI result back.
Otherwise CNI will fail with `unexpected end of JSON input`.

Fixes containers/podman#11413

Return the error message from gvproxy 
When gvproxy returns an error we should add the body to the error
message. For example this will now look like this:
`something went wrong with the request: "listen tcp 0.0.0.0:8080: bind:
address already in use\n`

Add gitignore
The bin directory should not be commited.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by bretonics** [comment]
Has this been merged with main podman? Experiencing the port issue on a fresh podman install, 3.3.1

**Comment by Luap99** [comment]
> Has this been merged with main podman? Experiencing the port issue on a fresh podman install, 3.3.1

Should be fixed when the podman 3.4 update lands in CoreOS

**Comment by ghost** [comment]
> Should be fixed when the podman 3.4 update lands in CoreOS

I'm using latest podman version and still getting this error

```
(base) ➜  ~ brew list podman
/usr/local/Cellar/podman/3.4.0_1/bin/podman
/usr/local/Cellar/podman/3.4.0_1/bin/podman-remote
/usr/local/Cellar/podman/3.4.0_1/etc/bash_completion.d/podman
/usr/local/Cellar/podman/3.4.0_1/libexec/gvproxy
/usr/local/Cellar/podman/3.4.0_1/share/fish/vendor_completions.d/podman.fish
/usr/local/Cellar/podman/3.4.0_1/share/man/ (160 files)
/usr/local/Cellar/podman/3.4.0_1/share/zsh/site-functions/_podman

(base) ➜  ~ podman run --rm nginx
Error: error preparing container 1eb7123707ecb48937319d63adb42fad9cc7781b45954dd5ef9957c505cf348c for attach: error configuring network namespace for container 1eb7123707ecb48937319d63adb42fad9cc7781b45954dd5ef9957c505cf348c: error adding pod nginx_nginx to CNI network "podman": unexpected end of JSON input
```

**Comment by tibcoplord** [comment]
I see the same with 3.4.0_1 on mac :

```
$ podman machine init
...
Downloading VM image: fedora-coreos-34.20211004.2.0-qemu.x86_64.qcow2.xz: done  
...
$ podman machine start
...
$ podman run --rm nginx
...
Error: error preparing container a87cf42040406a3eb17cd19604fa863226f2bd55a0334d9c277f9dc276e6b6b5 for attach: error configuring network namespace for container a87cf42040406a3eb17cd19604fa863226f2bd55a0334d9c277f9dc276e6b6b5: error adding pod goofy_lehmann_goofy_lehmann to CNI network "podman": unexpected end of JSON input
```

**Comment by cosmin** [comment]
You need podman 3.4 in the CoreOS version, not on the mac. Run

```
podman version
```

and see what it says for the server version. Apparently once that's 3.4 this should work (from what I've read).

**Comment by tibcoplord** [comment]
Ah, thanks ... but the server version is determined by machine init -

```
$ podman machine init
Downloading VM image: fedora-coreos-34.20211004.2.0-qemu.x86_64.qcow2.xz: done  
Extracting compressed file

$ podman machine start
INFO[0000] waiting for clients...                       
INFO[0000] listening tcp://0.0.0.0:7777                 
INFO[0000] new connection from  to /var/folders/ym/8x5zb6hx2t12gsq56_0vnl8c0000gn/T/podman/qemu_podman-machine-default.sock 
Waiting for VM ...
Machine "podman-machine-default" started successfully

$ podman version
Client:
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.17.1
Built:        Thu Sep 30 19:44:31 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Mon Aug 30 21:46:36 2021
OS/Arch:      linux/amd64
```

**Comment by cosmin** [comment]
Indeed, and my understanding is that we’re waiting for the next version to CoreOS with podman 3.4. Not sure whether there’s a way to upgrade the machine in place or whether that will require creating a new podman machine.

**Comment by tibcoplord** [comment]
Okay, thanks.

**Comment by tibcoplord** [comment]
fedora coreos 35.20211010.1.0 looks to have fixed the issue :

```
$ podman machine init --image-path next
Downloading VM image: fedora-coreos-35.20211010.1.0-qemu.x86_64.qcow2.xz: done  
Extracting compressed file

$ podman machine start
INFO[0000] waiting for clients...                       
INFO[0000] listening tcp://0.0.0.0:7777                 
INFO[0000] new connection from  to /var/folders/ym/8x5zb6hx2t12gsq56_0vnl8c0000gn/T/podman/qemu_podman-machine-default.sock 
Waiting for VM ...
2021/10/15 10:14:02 tcpproxy: for incoming conn [::1]:64101, error dialing "192.168.127.2:22": connect tcp 192.168.127.2:22: no route
2021/10/15 10:14:05 tcpproxy: for incoming conn [::1]:64105, error dialing "192.168.127.2:22": connect tcp 192.168.127.2:22: no route
2021/10/15 10:14:09 tcpproxy: for incoming conn [::1]:64108, error dialing "192.168.127.2:22": connect tcp 192.168.127.2:22: no route
2021/10/15 10:14:13 tcpproxy: for incoming conn [::1]:64111, error dialing "192.168.127.2:22": connect tcp 192.168.127.2:22: no route
2021/10/15 10:14:15 tcpproxy: for incoming conn [::1]:64116, error dialing "192.168.127.2:22": connect tcp 192.168.127.2:22: connection was refused
Machine "podman-machine-default" started successfully

$ podman version
Client:
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.17.1
Built:        Thu Sep 30 19:44:31 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 20:32:16 2021
OS/Arch:      linux/amd64

$ podman run --rm nginx
...
2021/10/15 09:16:48 [notice] 1#1: using the "epoll" event method
2021/10/15 09:16:48 [notice] 1#1: nginx/1.21.3
2021/10/15 09:16:48 [notice] 1#1: built by gcc 8.3.0 (Debian 8.3.0-6) 
2021/10/15 09:16:48 [notice] 1#1: OS: Linux 5.14.10-300.fc35.x86_64
2021/10/15 09:16:48 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 524288:524288
2021/10/15 09:16:48 [notice] 1#1: start worker processes
2021/10/15 09:16:48 [notice] 1#1: start worker process 26


```

**Pull request merged**
