### PR TITLE
Do not error on del command and output version information

### PR DESCRIPTION
**Pull request by Luap99**
#### Do not error on del command
According to the cni spec[1], a plugin should not return an error on
del. If a plugin returns an error cni will not call the following
plugins. Since the plugins are invoked in reverse order on del, the
portmapping and bridge plugins won't get invoked and therefore leave
iptables rules around.

[1] https://github.com/containernetworking/cni/blob/master/SPEC.md#del-remove-container-from-network-or-un-apply-modifications

#### Remove github.com/pkg/errors
There is no need for github.com/pkg/errors, we should stick with the native
errors package. To wrap errors we can use `fmt.Errorf("%w",err)`.

#### Output version information when called directly 
Include version and commit in output when called without the CNI args.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
-177k lines makes me happy. LGTM. I have no merge authority on this repo though.

**Comment by rhatdan** [comment]
@baude Looks like we could use a new release.

**Pull request merged**
